In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nibabel as nib
import timeit

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from MPC_tools import *

%matplotlib inline

In [2]:
base_dir = '/media/cocoan-gpu1/wani_8T/data/SEMIC'

In [3]:
dir_path_list, filenames_list = making_file_path(base_dir)

In [4]:
print(dir_path_list.shape)
print(dir_path_list)

(118,)
['/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic001'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic002'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic003'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic004'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic005'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic006'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic007'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic008'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic009'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic010'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic011'
 '/media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic01

In [5]:
print(len(filenames_list[59]))

2271


In [6]:
full_path_list = making_full_path_list(dir_path_list, filenames_list)

In [7]:
print(len(full_path_list[10]))

6051


In [8]:
total_index = np.arange(0,118)
total_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117])

In [9]:
load_index = np.delete(total_index, [17,55,56,57,58,75,114,115,116,117])
load_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113])

In [10]:
X, Y = load_nii(load_index, full_path_list, 50)

***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic001  ***


##########################################
###  Excecuted Time : 2.027630318996671  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic002  ***


##########################################
###  Excecuted Time : 4.875505666997924  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic003  ***


##########################################
###  Excecuted Time : 9.547852561001491  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic004  ***


##########################################
###  Excecuted Time : 16.076888306997716  ###
############

***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic033  ***


##########################################
###  Excecuted Time : 1070.443556667  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic034  ***


##########################################
###  Excecuted Time : 1134.0741983560001  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic035  ***


##########################################
###  Excecuted Time : 1200.0587027930014  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic036  ***


##########################################
###  Excecuted Time : 1267.4301304160035  ###
#############



##########################################
###  Excecuted Time : 4061.9659757780028  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_Overall_FIR_SPM_SINGLE_TRIAL/sub-semic011  ***


##########################################
###  Excecuted Time : 4190.175811337998  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_Overall_FIR_SPM_SINGLE_TRIAL/sub-semic012  ***


##########################################
###  Excecuted Time : 4319.8535260479985  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_Overall_FIR_SPM_SINGLE_TRIAL/sub-semic013  ***


##########################################
###  Excecuted Time : 4451.961424841  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/dat



##########################################
###  Excecuted Time : 8846.744624429994  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_Overall_FIR_SPM_SINGLE_TRIAL/sub-semic042  ***


##########################################
###  Excecuted Time : 9028.730537063995  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_Overall_FIR_SPM_SINGLE_TRIAL/sub-semic043  ***


##########################################
###  Excecuted Time : 9213.124192218995  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_Overall_FIR_SPM_SINGLE_TRIAL/sub-semic044  ***


##########################################
###  Excecuted Time : 9399.151266599001  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/da

In [11]:
X = flatten_nii(X)

***  Finished Flatten 1th Data  ***
###  Excecuted Time : 0.0027268499979982153  ###


***  Finished Flatten 101th Data  ***
###  Excecuted Time : 3.9991990589915076  ###


***  Finished Flatten 201th Data  ***
###  Excecuted Time : 15.357115671999054  ###


***  Finished Flatten 301th Data  ***
###  Excecuted Time : 34.45085603700136  ###


***  Finished Flatten 401th Data  ***
###  Excecuted Time : 61.13953736900294  ###


***  Finished Flatten 501th Data  ***
###  Excecuted Time : 95.5729258240026  ###


***  Finished Flatten 601th Data  ***
###  Excecuted Time : 137.23108845899696  ###


***  Finished Flatten 701th Data  ***
###  Excecuted Time : 185.78370237599302  ###


***  Finished Flatten 801th Data  ***
###  Excecuted Time : 242.2602724180033  ###


***  Finished Flatten 901th Data  ***
###  Excecuted Time : 306.40504294600396  ###


***  Finished Flatten 1001th Data  ***
###  Excecuted Time : 377.0759600099991  ###


***  Finished Flatten 1101th Data  ***
###  Excecuted Time

In [12]:
y = pd.DataFrame(data=Y, dtype=np.float32)

# Logistic Regression Model

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [14]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
print(classification_report(y_test, predictions))

/home/cocoan-gpu1/anaconda3/envs/tf3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/cocoan-gpu1/anaconda3/envs/tf3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

         0.0       0.98      0.96      0.97       827
         1.0       0.96      0.98      0.97       823

   micro avg       0.97      0.97      0.97      1650
   macro avg       0.97      0.97      0.97      1650
weighted avg       0.97      0.97      0.97      1650



In [15]:
conf_mat = confusion_matrix(y_test, predictions)
print(conf_mat)
acc = (conf_mat[0,0]+conf_mat[1,1])/conf_mat.sum()
print(acc)

[[795  32]
 [ 19 804]]
0.9690909090909091


# Load new data

In [16]:
load_new_index=[55,56,57,58,114,115,116,117]
new_X, new_Y = load_nii(load_new_index, full_path_list, 50)
new_X = flatten_nii(new_X)

***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic056  ***


##########################################
###  Excecuted Time : 2.5727997200010577  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic057  ***


##########################################
###  Excecuted Time : 7.595917547994759  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic058  ***


##########################################
###  Excecuted Time : 14.526392674000817  ###
##########################################


***  Finished Loading 1th Nii File In /media/cocoan-gpu1/wani_8T/data/SEMIC/model02_FIR_SPM_SINGLE_TRIAL/sub-semic059  ***


##########################################
###  Excecuted Time : 23.225253786004032  ###
##########

In [17]:
new_Y = pd.DataFrame(data=new_Y, dtype=np.float32)

In [19]:
predictions_new = logmodel.predict(new_X)
print(classification_report(new_Y, predictions_new))

              precision    recall  f1-score   support

         0.0       0.95      0.94      0.94       200
         1.0       0.94      0.95      0.95       200

   micro avg       0.94      0.94      0.94       400
   macro avg       0.95      0.94      0.94       400
weighted avg       0.95      0.94      0.94       400



In [36]:
conf_mat_new = confusion_matrix(new_Y, predictions_new)
print(conf_mat_new[1,0])

10


In [41]:
data_conf = pd.DataFrame(conf_mat, index=['True_Negative','True_Positive'], columns=['Pred_Negative','Pred_Positive'])

In [42]:
data_conf

Pred_Negative  Pred_Positive
True_Negative            795             32
True_Positive             19            804

In [43]:
acc = (conf_mat[0,0]+conf_mat[1,1])/conf_mat.sum()
print(acc)

0.9690909090909091


In [39]:
new_data_conf = pd.DataFrame(conf_mat_new, index=['True_Negative','True_Positive'], columns=['Pred_Negative','Pred_Positive'])

In [40]:
new_data_conf

Pred_Negative  Pred_Positive
True_Negative            188             12
True_Positive             10            190

In [22]:
acc_new = (conf_mat_new[0,0]+conf_mat_new[1,1])/conf_mat_new.sum()
print(acc_new)

0.945


In [24]:
np.save('/home/cocoan-gpu1/Documents/Deep_pain_connectome/sungwoo/SEMIC_sub1to55_num1to50_stim_control_flatten', X)

In [30]:
y.to_csv('/home/cocoan-gpu1/Documents/Deep_pain_connectome/sungwoo/SEMIC_sub1to55_num1to50_stim_control_pandas.csv')

In [26]:
np.save('/home/cocoan-gpu1/Documents/Deep_pain_connectome/sungwoo/SEMIC_sub56to59_num1to50_stim_control_flatten', new_X)

In [31]:
new_Y.to_csv('/home/cocoan-gpu1/Documents/Deep_pain_connectome/sungwoo/SEMIC_sub56to59_num1to50_stim_control_pandas.csv')